### ISSUE TITLE
Downloaded files have random names!

### ISSUE THREAD

**Issue by Irwin86** [realcoloride/TwitterDL#1]
It is possible to modify and improve this script to download videos from twitter with regular names like userID, tweet ID etc., for example: The filename pattern looks so: [twitter] {author}—{YYYY.MM.DD}—{id}—{filename}.{extension}. 

This will be very helpful to make downloaded files well organised and save time, and it would make this tool more attractive and useful.

**Comment by realcoloride** [comment]
Hello! Thanks for your feedback - This will be definetely be considered.
I will think about a way to name the files that is short and conveniant.

I will hit you back soon!

**Comment by realcoloride** [comment]
Hello, I've implemented the current format:
`TwitterDL-${username}-${tweetId}.${extension}`;

Please drop me your feedback! If good, I will push an update soon.

**Comment by realcoloride** [comment]
Hello, I have replaced the dashes (-) with underscores (_). I've also fixed some extra stuff and I pushed the `1.0.4` update with file names. Please let me know how it goes!

You should receive an popup telling you to update soon.

**Comment by realcoloride** [comment]
Hello, I've noticed a strange underscore at the end of the filenames, I will resolve that now.
EDIT: Resolved with version 1.0.6

**Comment by Irwin86** [comment]
You are a real genius and awesome!!! I do find the magic you have done and updated for this tool, it really works well now!! Every video I download from Twitter has its name with userID, tweetID, thank you very much!!!!

**Comment by Irwin86** [comment]
I also got some good ideas to improve this tool which will make it Awesome, I do really hope I can contribute my efforts and work to your script, but I do not have a well-built and developed coding knowledge and skills like you, so I will try to use Copilot to assist

**Comment by Irwin86** [comment]
> Hello, I've noticed a strange underscore at the end of the filenames, I will resolve that now. EDIT: Resolved with version 1.0.6

I will share my ideas to you here soon later

**Comment by realcoloride** [comment]
Hello and thank you for the kind words and support, I really appreciate it!

Side note, if you like this script and want something like that for YouTube, check out my brand new script: https://github.com/realcoloride/YoutubeDL

If you wish to suggest anything or report a problem, feel free to open an new issue.
If you feel like this issue has been resolved to you, feel free to close this issue.
