### ISSUE TITLE
Doesn't work for private twitter account??

### ISSUE THREAD

**Issue by Irwin86** [realcoloride/TwitterDL#2]
This script is greatly improved since the first issue has been fixed, but I just realised that it doesn't work for a private Twitter account which I have followed and can see their tweets and content, is this possible to be fixed since it probably involves different API??? hope you don't mind the term I use blindly....  I know nothing about programming...

**Comment by Irwin86** [comment]
Some ideas I'd like to share with you, this script used to work perfectly before Twitter change something, this script allow users to choose wider range of resolution from low quality to high original quality like 2140 x 1080 etc., and its UI look neat and easier which it shows the download optional button in the video's right corner with small space, it can download gifs on twitter etc, maybe this script can inspire you a bit to further improve?

**Comment by Irwin86** [comment]
I mean this scrpit: https://greasyfork.org/en/scripts/390723-twitter-download-gif-video

**Comment by Irwin86** [comment]
It uses a transparent and scalable button to make it look neat, well I know everyone's aesthetics is different, If I have coding skills, I would copy the scripts and modify it to work what I want it to do

**Comment by realcoloride** [comment]
Hello there,
Sadly due to the API i'm using its impossible to get qualities other than high and low or fetch through private accounts. 

I'm sorry!

**Comment by Irwin86** [comment]
Hey, don't say sorry, sir!!! You are have done a lot to people for this script, we should thank you a lot, I suggest you to share your donate page or Crypto receiving address, so people will be able to send you their support and love, I'm broke for a while, but if I get money again I will be sure to send some support for you.

**Comment by Irwin86** [comment]
Again, I find the modification you made for re-naming when downloading twitter video doesn't work anymore, what's wrong with it though? It becomes random names again for the downloaded files

**Comment by Irwin86** [comment]
> Hey, don't say sorry, sir!!! You are have done a lot to people for this script, we should thank you a lot, I suggest you to share your donate page or Crypto receiving address, so people will be able to send you their support and love, I'm broke for a while, but if I get money again I will be sure to send some support for you.

You have done a lot of work for this script, as users we really appreciate you!!!!

**Comment by realcoloride** [comment]
Hello there,

Thank you for your support. I'd kindly accept donations if some people want
to support me but haven't thought about it and will look into it. That
means a lot to me.
Know that my scripts will stay free, open source and non profit to all.

If you're having issue with filenames again, perhaps try reinstalling to
the plugin or updating to the latest version or simply refreshing the page.
If that doesn't work I will look further into the issue.

Good luck!

**Comment by Irwin86** [comment]
It improved again, the file name works well now, thank you very much again.
